services:
  - type: web
    name: canada-tracker-web
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://canada-tracker-api.onrender.com/api
