#!/bin/bash

echo "🚀 Canada Days Tracker - Deployment Helper"
echo "=========================================="
echo ""

# Check if git is configured
if ! git config --global user.name > /dev/null 2>&1; then
    echo "⚠️  Git not configured. Please run:"
    echo "   git config --global user.name 'Your Name'"
    echo "   git config --global user.email 'your.email@example.com'"
    echo ""
fi

# Check if code is committed
if [ -n "$(git status --porcelain)" ]; then
    echo "⚠️  You have uncommitted changes. Please commit them first:"
    echo "   git add . && git commit -m 'Your commit message'"
    echo ""
fi

echo "📋 Deployment Steps:"
echo ""
echo "1. 🌐 Create GitHub Repository:"
echo "   - Go to https://github.com/new"
echo "   - Name: canada-days-tracker"
echo "   - Make it public or private"
echo "   - Don't initialize with README (we already have one)"
echo ""
echo "2. 📤 Push to GitHub:"
echo "   git remote add origin https://github.com/YOUR_USERNAME/canada-days-tracker.git"
echo "   git branch -M main"
echo "   git push -u origin main"
echo ""
echo "3. 🗄️  Set up Database (Neon):"
echo "   - Go to https://neon.tech"
echo "   - Create account and new project"
echo "   - Copy the connection string"
echo ""
echo "4. 🔧 Deploy Backend (Render):"
echo "   - Go to https://render.com"
echo "   - Connect your GitHub repo"
echo "   - Create Web Service"
echo "   - Build Command: cd apps/api && npm install && npm run build"
echo "   - Start Command: cd apps/api && npm start"
echo "   - Add DATABASE_URL environment variable"
echo ""
echo "5. 🎨 Deploy Frontend (Vercel):"
echo "   - Go to https://vercel.com"
echo "   - Import your GitHub repo"
echo "   - Root Directory: apps/web"
echo "   - Add VITE_API_URL environment variable"
echo ""
echo "6. 🗃️  Run Database Migration:"
echo "   - In Render Shell:"
echo "     cd apps/api"
echo "     npx prisma generate"
echo "     npx prisma db push"
echo ""
echo "📖 For detailed instructions, see DEPLOYMENT.md"
echo ""
echo "🎉 Your app will be live and accessible from anywhere!"
echo ""
echo "Need help? Check the troubleshooting section in DEPLOYMENT.md"
