services:
  # Backend API Service
  - type: web
    name: canada-tracker-api
    env: node
    rootDir: apps/api
    buildCommand: npm install && npm run generate && npm run db:deploy && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
    healthCheckPath: /api/health

  # Frontend Web Service
  - type: web
    name: canada-tracker-web
    env: static
    rootDir: apps/web
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://canada-tracker-api.onrender.com/api
