services:
  - type: web
    name: canada-tracker-api
    env: node
    buildCommand: npm install && npm run generate && npm run db:deploy && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
    healthCheckPath: /api/health
